version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - sam package --template-file petstore-api.yaml
                                   --s3-bucket aws-codepipeline-bucket-experiments
                                   --s3-prefix api-code
                                   --output-template-file petstore-api-output.yaml
artifacts:
  type: zip
  files:
    - 01api/petstore-api-output.yaml
