version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      
  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --template-file petstore-api.yaml
                                   --s3-bucket aws-codepipeline-bucket-experiments
                                   --s3-prefix api-code
                                   --output-template-file petstore-api-output.yaml
artifacts:
  type: zip
  files:
    - 01api/petstore-api-output.yaml
